version: "3"
services:
  django:
    container_name: mitempjj4
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: mitempjj4
    stdin_open: true
    tty: true
    volumes:
      - ./database/:/opt/app/mitempjj/database/
    ports:
      - "8083:8083"
